from __future__ import division

import numpy as np
import pylab as plt
import scipy.special   as sp 
import scipy.integrate as si
from mpl_toolkits.mplot3d import Axes3D

# Plot data array generated by ellipticalCylinder.py

data = np.load('dataSet1.npy')

fig=plt.figure()
ax = fig.add_subplot(111,projection='3d')

ax.scatter(data[:,0]*180/(np.pi),data[:,1],data[:,2])
plt.show()


